// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmy5oyydEl3OC3qjeKw6LRJayjvYZGl2k',
    appId: '1:758486038409:web:f6926f0029cf6ec6b45358',
    messagingSenderId: '758486038409',
    projectId: 'finpro-edspert-app',
    authDomain: 'finpro-edspert-app.firebaseapp.com',
    storageBucket: 'finpro-edspert-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdpEuI4HOiXoxuBM2RoKJOZhCnAl4WQL0',
    appId: '1:758486038409:android:ca97181dec931b15b45358',
    messagingSenderId: '758486038409',
    projectId: 'finpro-edspert-app',
    storageBucket: 'finpro-edspert-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcyNvg--M3dz2xep6qsb3P3LpgtFRX90w',
    appId: '1:758486038409:ios:0c48998429182811b45358',
    messagingSenderId: '758486038409',
    projectId: 'finpro-edspert-app',
    storageBucket: 'finpro-edspert-app.appspot.com',
    iosClientId: '758486038409-esn5qvt8hnot7evnqacoh47smd37cdvg.apps.googleusercontent.com',
    iosBundleId: 'com.example.finproEdspert17David',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcyNvg--M3dz2xep6qsb3P3LpgtFRX90w',
    appId: '1:758486038409:ios:d4ea1cbd101d7c27b45358',
    messagingSenderId: '758486038409',
    projectId: 'finpro-edspert-app',
    storageBucket: 'finpro-edspert-app.appspot.com',
    iosClientId: '758486038409-i4porjf7abqq4pake14q2535ek6834ga.apps.googleusercontent.com',
    iosBundleId: 'com.example.finproEdspert17David.RunnerTests',
  );
}
